### ISSUE TITLE
 Meets status to be added (upcoming, ongoing, finished)

### ISSUE THREAD

**Issue by shashankp4nda** [ssncodingclub/Coding-Club-Website#44]
edit the meets data and add a field to mention the status of the meet ( whether it's upcoming, ongoing or finished ). edit the meets card to reflect this status in the form of a small, color-coded tag. 
view https://www.ssncc.tech/meets to see mentioned meets-card.

**Comment by charu210703** [comment]
can I pick this up? I would like to work on this if its not assigned to anybody else.

**Comment by shashankp4nda** [comment]
sure, assigning it to you now.
